platform :ios, '14.0'
use_frameworks!

#source 'https://gitlab.com/XPstocks/ios/public/XPpodspec.git'
#source 'https://gitlab.com/XPstocks/XPpodspec.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitee.com:jamalping/xpspecs.git'

target 'XPUIKit_Example' do

  pod 'XPUIKit', :path => '../'

  # pod 'Base', :path => '../'
  # pod 'Network', '~> 0.1.0'

  # target 'XPUIKit_Tests' do
  #   inherit! :search_paths
  #
  #
  # end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end

#post_install do |installer|
#    installer.generated_projects.each do |project|
#          project.targets.each do |target|
#              target.build_configurations.each do |config|
#                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
#               end
#          end
#   end
#end
